// <auto-generated />
using AgendaContactos.BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AgendaContactos.BackEnd.Migrations
{
    [DbContext(typeof(AgendaDb))]
    partial class AgendaDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agenda.BackEnd.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Correo");

                    b.Property<string>("Direccion");

                    b.Property<string>("NombreApe");

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Agenda.BackEnd.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Agenda.BackEnd.Models.GrupoContactos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactoId");

                    b.Property<int>("GrupoId");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("GruposContactos");
                });

            modelBuilder.Entity("Agenda.BackEnd.Models.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactoId");

                    b.Property<string>("Numero");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("Agenda.BackEnd.Models.GrupoContactos", b =>
                {
                    b.HasOne("Agenda.BackEnd.Models.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agenda.BackEnd.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agenda.BackEnd.Models.Telefono", b =>
                {
                    b.HasOne("Agenda.BackEnd.Models.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
